apiVersion: apps/v1
kind: Deployment
metadata:
  name: shs-dep
  labels:
    app: shs-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shs-pod
  template:
    metadata:
      labels:
        app: shs-pod
    spec:
      containers:
        - name: http-server
          image: ghcr.io/feiyudev/shs:latest
          ports:
            - containerPort: 80
            - containerPort: 8080
            - containerPort: 8081
          command:
            - "/root/simple-http-server"
          args:
            - "--port"
            - "80"
            - "--port"
            - "8080"
            - "--port"
            - "8081"
          imagePullPolicy: IfNotPresent
          resources:
            limits:
              cpu: 500m
              memory: 500Mi
            requests:
              cpu: 50m
              memory: 50Mi
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: shs-svc
  name: shs-svc
spec:
  ports:
  - name: shs-80
    port: 80
    protocol: TCP
    targetPort: 80
  - name: shs-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  - name: shs-8081
    port: 8081
    protocol: TCP
    targetPort: 8081
  selector:
    app: shs-pod
  type: NodePort
